### ISSUE TITLE
Proposed test asset storage

### ISSUE THREAD

**Issue by adam4813** [project-trillek-archive/trillek-client-core#19]
I am proposing we store the test asset files in a root folder within tests eg tests/test_assets. Then during the automated build (Travis CI) it would copy the folder to the binary folder. Then anytime an asset is needed it must be loaded from ./test_assets/.

**Comment by DeVaukz** [comment]
This is fine as a stop-gap but at some point we need to cleanup resource loading.  Add a function that returns the path to the resources directory and load all resources relative to that path. Alternatively, set the working directory to the resources path at program startup.

We need to do this because certain platforms, such as OS X, do not set the working directory to the executable folder when the program is launched normally.  And even if it did, Resources should be stored in ../Resources relative to the executable (on OS X).

**Comment by ghost** [comment]
Adding to this: executables in packaged programs in Linux are in `/usr/bin`, and assets - `/usr/share`.

**Comment by Zardoz89** [comment]
We are going to store all test assets in the repository ?

**Comment by adam4813** [comment]
This would only apply to the tests and not the full game.

Zardoz89 suggested storing them on a server and wget them which might be the best solution for Travis.

**Comment by adam4813** [comment]
Let's just put them in a sub module.

**Comment by adam4813** [comment]
It is now a sub module.
